meta:
  lang: en
  locale: en_US
  title: 'Andrea Mangano - Personal website'
  description: 'Andrea Mangano - UI/Web Developer - Resume'
  canonicalUrl: http://andreamangano.com
  twitterProfile: andreaman87

links:
  - type: email
    href: andreaman87@gmail.com
    label: Mail me
  - type: twitter
    href: https://twitter.com/andreaman87
    label: Twitter
  - type: linkedin
    href: https://it.linkedin.com/in/manganoandrea
    label: Linkedin
  - type: github
    href: https://github.com/andreamangano
    label: Github

footer:
  quote: “A dream you dream alone is only a dream. A dream you dream together is reality.” — John Lennon
  copyright: >
             Andrea Mangano / Copyright ©2017.
             Created with passion &
             <a href="https://github.com/andreamangano/andreamangano.com" target="_blank">several lines of code</a>.